package oracle_demo

import "testing"

// https://baike.baidu.com/item/%E5%9F%BA%E6%95%B0%E8%AF%8D
var ordinal_num map[int]string

// https://baike.baidu.com/item/%E5%BA%8F%E6%95%B0%E8%AF%8D/3811128
var cardinal_num map[int]string

func init() {

	ordinal_num = map[int]string{
		1:             "one",
		2:             "two",
		3:             "three",
		4:             "four",
		5:             "five",
		6:             "six",
		7:             "seven",
		8:             "eight",
		9:             "nine",
		10:            "ten",
		11:            "eleven",
		12:            "twelve",
		13:            "thirteen",
		14:            "fourteen",
		15:            "fifteen",
		16:            "sixteen",
		17:            "seventeen",
		18:            "eighteen",
		19:            "nineteen",
		20:            "twenty",
		21:            "twenty-one",
		22:            "twenty-two",
		23:            "twenty-three",
		24:            "twenty-four",
		25:            "twenty-five",
		26:            "twenty-six",
		27:            "twenty-seven",
		28:            "twenty-eight",
		29:            "twenty-nine",
		30:            "thirty",
		31:            "thirty-one",
		32:            "thirty-two",
		33:            "thirty-three",
		34:            "thirty-four",
		35:            "thirty-five",
		36:            "thirty-six",
		37:            "thirty-seven",
		38:            "thirty-eight",
		39:            "thirty-nine",
		40:            "forty",
		41:            "forty-one",
		42:            "forty-two",
		43:            "forty-three",
		44:            "forty-four",
		45:            "forty-five",
		46:            "forty-six",
		47:            "forty-seven",
		48:            "forty-eight",
		49:            "forty-nine",
		50:            "fifty",
		51:            "fifty-one",
		52:            "fifty-two",
		53:            "fifty-three",
		54:            "fifty-four",
		55:            "fifty-five",
		56:            "fifty-six",
		57:            "fifty-seven",
		58:            "fifty-eight",
		59:            "fifty-nine",
		60:            "sixty",
		61:            "sixty-one",
		62:            "sixty-two",
		63:            "sixty-three",
		64:            "sixty-four",
		65:            "sixty-five",
		66:            "sixty-six",
		67:            "sixty-seven",
		68:            "sixty-eight",
		69:            "sixty-nine",
		70:            "seventy",
		71:            "seventy-one",
		72:            "seventy-two",
		73:            "seventy-three",
		74:            "seventy-four",
		75:            "seventy-five",
		76:            "seventy-six",
		77:            "seventy-seven",
		78:            "seventy-eight",
		79:            "seventy-nine",
		80:            "eighty",
		81:            "eighty-one",
		82:            "eighty-two",
		83:            "eighty-three",
		84:            "eighty-four",
		85:            "eighty-five",
		86:            "eighty-six",
		87:            "eighty-seven",
		88:            "eighty-eight",
		89:            "eighty-nine",
		90:            "ninety",
		91:            "ninety-one",
		92:            "ninety-two",
		93:            "ninety-three",
		94:            "ninety-four",
		95:            "ninety-five",
		96:            "ninety-six",
		97:            "ninety-seven",
		98:            "ninety-eight",
		99:            "ninety-nine",
		100:           "hundred",
		1000:          "thousand",
		1000000:       "million",
		1000000000:    "billion",
		1000000000000: "trillion",
	}

	cardinal_num = map[int]string{
		1:   "first",
		2:   "second",
		3:   "third",
		4:   "fourth",
		5:   "fifth",
		6:   "sixth",
		7:   "seventh",
		8:   "eighth",
		9:   "ninth",
		10:  "tenth",
		11:  "eleventh",
		12:  "twelfth",
		13:  "thirteenth",
		14:  "fourteenth",
		15:  "fifteenth",
		16:  "sixteenth",
		17:  "seventeenth",
		18:  "eighteenth",
		19:  "nineteenth",
		20:  "twentieth",
		21:  "twenty-first",
		22:  "twenty-second",
		23:  "twenty-third",
		24:  "twenty-fourth",
		25:  "twenty-fifth",
		26:  "twenty-sixth",
		27:  "twenty-seventh",
		28:  "twenty-eighth",
		29:  "twenty-ninth",
		30:  "thirtieth",
		31:  "thirty-first",
		32:  "thirty-second",
		33:  "thirty-third",
		34:  "thirty-fourth",
		35:  "thirty-fifth",
		36:  "thirty-sixth",
		37:  "thirty-seventh",
		38:  "thirty-eighth",
		39:  "thirty-ninth",
		40:  "fortieth",
		41:  "forty-first",
		42:  "forty-second",
		43:  "forty-third",
		44:  "forty-fourth",
		45:  "forty-fifth",
		46:  "forty-sixth",
		47:  "forty-seventh",
		48:  "forty-eighth",
		49:  "forty-ninth",
		50:  "fiftieth",
		51:  "fifty-first",
		52:  "fifty-second",
		53:  "fifty-third",
		54:  "fifty-fourth",
		55:  "fifty-fifth",
		56:  "fifty-sixth",
		57:  "fifty-seventh",
		58:  "fifty-eighth",
		59:  "fifty-ninth",
		60:  "sixtieth",
		61:  "sixty-first",
		62:  "sixty-second",
		63:  "sixty-third",
		64:  "sixty-fourth",
		65:  "sixty-fifth",
		66:  "sixty-sixth",
		67:  "sixty-seventh",
		68:  "sixty-eighth",
		69:  "sixty-ninth",
		70:  "seventieth",
		71:  "seventy-first",
		72:  "seventy-second",
		73:  "seventy-third",
		74:  "seventy-fourth",
		75:  "seventy-fifth",
		76:  "seventy-sixth",
		77:  "seventy-seventh",
		78:  "seventy-eighth",
		79:  "seventy-ninth",
		80:  "eightieth",
		81:  "eightieth-first",
		82:  "eightieth-second",
		83:  "eightieth-third",
		84:  "eightieth-fourth",
		85:  "eightieth-fifth",
		86:  "eightieth-sixth",
		87:  "eightieth-seventh",
		88:  "eightieth-eighth",
		89:  "eightieth-ninth",
		90:  "ninetieth",
		91:  "ninetieth-first",
		92:  "ninetieth-second",
		93:  "ninetieth-third",
		94:  "ninetieth-fourth",
		95:  "ninetieth-fifth",
		96:  "ninetieth-sixth",
		97:  "ninetieth-seventh",
		98:  "ninetieth-eighth",
		99:  "ninetieth-ninth",
		100: "one hundredth",
	}

}

func TestCardinalNum2OrdinalNum(t *testing.T) {

}

func TestOrdinalNum2CardinalNum(t *testing.T) {

}
