// Code generated by cmd/cgo; DO NOT EDIT.

//line /Users/mac/save/code/golang/golang_practice/cgo_demo/demo2/main.go:1:1
package main

//#include "stdio.h"
import _ "unsafe"
import "fmt"

func main() {
	fmt.Println(( /*line :8:14*/_Cfunc_GoString /*line :8:23*/)(( /*line :8:25*/_Cfunc_CString /*line :8:33*/)("cgo Hello World")))
}
